Sender: LSF System <lsfadmin@zhcc005>
Subject: Job 777176: <python3 trainer_resnet.py -seed=1 -batch_size=256 -weight_decay=0.0005 -momentum=0.9 -save_every=10 -lr=0.1 -n_attack_steps=10 -beta_robustness=0.0 -gamma=0.0 -eps_pga=0.0 -eta_train=0.075 -eta_mode=ind -clipping_alpha=2.0 -attack_size_mismatch=0.2 -initial_std=0.001 -pretrained -burn_in=0 -workers=4 -n_epochs=300 -dataset=cifar10 -architecture=resnet32 -start_epoch=60 -data_dir=/dataP/jbu -session_id=7428207086> in cluster <ZHC2clusterLSF> Exited

Job <python3 trainer_resnet.py -seed=1 -batch_size=256 -weight_decay=0.0005 -momentum=0.9 -save_every=10 -lr=0.1 -n_attack_steps=10 -beta_robustness=0.0 -gamma=0.0 -eps_pga=0.0 -eta_train=0.075 -eta_mode=ind -clipping_alpha=2.0 -attack_size_mismatch=0.2 -initial_std=0.001 -pretrained -burn_in=0 -workers=4 -n_epochs=300 -dataset=cifar10 -architecture=resnet32 -start_epoch=60 -data_dir=/dataP/jbu -session_id=7428207086> was submitted from host <zhcc022> by user <jbu> in cluster <ZHC2clusterLSF> at Tue Nov 23 12:49:16 2021
Job was executed on host(s) <zhcc005>, in queue <prod.med>, as user <jbu> in cluster <ZHC2clusterLSF> at Tue Nov 23 12:49:17 2021
</u/jbu> was used as the home directory.
</u/jbu/Resnet32-ICLR> was used as the working directory.
Started at Tue Nov 23 12:49:17 2021
Terminated at Tue Nov 23 12:50:33 2021
Results reported at Tue Nov 23 12:50:33 2021

Your job looked like:

------------------------------------------------------------
# LSBATCH: User input
python3 trainer_resnet.py -seed=1 -batch_size=256 -weight_decay=0.0005 -momentum=0.9 -save_every=10 -lr=0.1 -n_attack_steps=10 -beta_robustness=0.0 -gamma=0.0 -eps_pga=0.0 -eta_train=0.075 -eta_mode=ind -clipping_alpha=2.0 -attack_size_mismatch=0.2 -initial_std=0.001 -pretrained -burn_in=0 -workers=4 -n_epochs=300 -dataset=cifar10 -architecture=resnet32 -start_epoch=60 -data_dir=/dataP/jbu -session_id=7428207086
------------------------------------------------------------

TERM_OWNER: job killed by owner.
Exited with exit code 1.

Resource usage summary:

    CPU time :                                   224.25 sec.
    Max Memory :                                 2047 MB
    Average Memory :                             1731.00 MB
    Total Requested Memory :                     -
    Delta Memory :                               -
    Max Swap :                                   -
    Max Processes :                              7
    Max Threads :                                133
    Run time :                                   77 sec.
    Turnaround time :                            77 sec.

The output (if any) follows:

Loaded pretrained model from /ibm/gpfs-homes/jbu/Resnet32-ICLR/Resources/cifar10_pretrained_models/resnet32.th
Files already downloaded and verified
Files already downloaded and verified
Files already downloaded and verified
/u/jbu/.conda/envs/msc/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:136: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
 * Prec@1 99.440
 * Prec@1 14.440
 * Prec@1 14.460
 * Prec@1 15.620
 * Prec@1 14.000
 * Noisy Prec@1 14.69
After loading, with clipping@2.00 14.44 w/o 99.44 noisy: 14.69pm0.83
current lr 2.00000e-02
Epoch: [60][0/176]	Time 0.704 (0.704)	Data 0.606 (0.606)	Loss 0.9046 (0.9046)	Prec@1 88.672 (88.672)
Epoch: [60][17/176]	Time 0.071 (0.115)	Data 0.001 (0.035)	Loss 0.7494 (0.7992)	Prec@1 88.281 (90.082)
Epoch: [60][34/176]	Time 0.071 (0.099)	Data 0.001 (0.019)	Loss 0.7449 (0.7500)	Prec@1 87.500 (89.609)
Epoch: [60][51/176]	Time 0.071 (0.090)	Data 0.001 (0.013)	Loss 0.5120 (0.7015)	Prec@1 94.141 (90.054)
Epoch: [60][68/176]	Time 0.071 (0.086)	Data 0.001 (0.010)	Loss 0.5037 (0.6568)	Prec@1 94.922 (90.902)
Epoch: [60][85/176]	Time 0.080 (0.083)	Data 0.003 (0.008)	Loss 0.6504 (0.6240)	Prec@1 92.578 (91.574)
Epoch: [60][102/176]	Time 0.072 (0.081)	Data 0.001 (0.007)	Loss 0.4703 (0.6101)	Prec@1 94.531 (91.778)
Epoch: [60][119/176]	Time 0.071 (0.080)	Data 0.001 (0.006)	Loss 0.4667 (0.5938)	Prec@1 94.141 (92.005)
Epoch: [60][136/176]	Time 0.071 (0.079)	Data 0.001 (0.006)	Loss 0.5449 (0.5796)	Prec@1 92.969 (92.287)
Epoch: [60][153/176]	Time 0.071 (0.078)	Data 0.001 (0.005)	Loss 0.4666 (0.5680)	Prec@1 95.312 (92.487)
Epoch: [60][170/176]	Time 0.071 (0.078)	Data 0.000 (0.005)	Loss 0.5664 (0.5584)	Prec@1 91.016 (92.656)
 * Prec@1 85.960
 * Prec@1 83.920
 * Prec@1 81.480
 * Prec@1 82.760
 * Noisy Prec@1 82.72
	 * New best: 82.72000
current lr 2.00000e-02
Epoch: [61][0/176]	Time 0.502 (0.502)	Data 0.429 (0.429)	Loss 0.4822 (0.4822)	Prec@1 93.359 (93.359)
Epoch: [61][17/176]	Time 0.071 (0.099)	Data 0.001 (0.025)	Loss 0.4333 (0.4649)	Prec@1 95.312 (93.924)
Epoch: [61][34/176]	Time 0.071 (0.085)	Data 0.001 (0.014)	Loss 0.3564 (0.4630)	Prec@1 96.875 (94.196)
Epoch: [61][51/176]	Time 0.071 (0.081)	Data 0.001 (0.010)	Loss 0.3652 (0.4594)	Prec@1 96.484 (94.201)
Epoch: [61][68/176]	Time 0.072 (0.079)	Data 0.001 (0.007)	Loss 0.4025 (0.4509)	Prec@1 94.922 (94.322)
Epoch: [61][85/176]	Time 0.071 (0.077)	Data 0.001 (0.006)	Loss 0.4125 (0.4503)	Prec@1 94.922 (94.409)
Epoch: [61][102/176]	Time 0.071 (0.076)	Data 0.001 (0.005)	Loss 0.4648 (0.4489)	Prec@1 93.750 (94.383)
Epoch: [61][119/176]	Time 0.071 (0.075)	Data 0.001 (0.005)	Loss 0.4278 (0.4475)	Prec@1 93.750 (94.391)
Epoch: [61][136/176]	Time 0.071 (0.075)	Data 0.001 (0.004)	Loss 0.4816 (0.4470)	Prec@1 91.797 (94.400)
Epoch: [61][153/176]	Time 0.071 (0.074)	Data 0.001 (0.004)	Loss 0.4271 (0.4463)	Prec@1 94.141 (94.369)
Epoch: [61][170/176]	Time 0.077 (0.074)	Data 0.000 (0.004)	Loss 0.4118 (0.4461)	Prec@1 94.922 (94.344)
 * Prec@1 89.220
 * Prec@1 89.460
 * Prec@1 89.480
 * Prec@1 89.200
 * Noisy Prec@1 89.38
	 * New best: 89.38000
current lr 2.00000e-02
Epoch: [62][0/176]	Time 0.543 (0.543)	Data 0.472 (0.472)	Loss 0.5394 (0.5394)	Prec@1 92.578 (92.578)
Epoch: [62][17/176]	Time 0.071 (0.098)	Data 0.001 (0.027)	Loss 0.4912 (0.4009)	Prec@1 94.141 (95.182)
Epoch: [62][34/176]	Time 0.071 (0.085)	Data 0.001 (0.015)	Loss 0.4742 (0.4072)	Prec@1 92.578 (95.123)
Epoch: [62][51/176]	Time 0.071 (0.080)	Data 0.001 (0.010)	Loss 0.5089 (0.4142)	Prec@1 91.406 (94.839)
Epoch: [62][68/176]	Time 0.071 (0.078)	Data 0.001 (0.008)	Loss 0.4322 (0.4098)	Prec@1 94.141 (94.945)
Epoch: [62][85/176]	Time 0.072 (0.078)	Data 0.001 (0.007)	Loss 0.4213 (0.4152)	Prec@1 95.312 (94.845)
Epoch: [62][102/176]	Time 0.074 (0.077)	Data 0.001 (0.006)	Loss 0.4887 (0.4155)	Prec@1 91.016 (94.804)
Epoch: [62][119/176]	Time 0.071 (0.076)	Data 0.001 (0.005)	Loss 0.3859 (0.4135)	Prec@1 95.703 (94.743)
Epoch: [62][136/176]	Time 0.071 (0.076)	Data 0.001 (0.005)	Loss 0.4409 (0.4151)	Prec@1 94.922 (94.671)
Epoch: [62][153/176]	Time 0.071 (0.075)	Data 0.001 (0.004)	Loss 0.3328 (0.4169)	Prec@1 96.875 (94.607)
Epoch: [62][170/176]	Time 0.069 (0.075)	Data 0.000 (0.004)	Loss 0.3884 (0.4168)	Prec@1 95.703 (94.577)
 * Prec@1 87.060
 * Prec@1 87.400
Exception ignored in: <function _releaseLock at 0x1002861cacb0>
Traceback (most recent call last):
  File "/u/jbu/.conda/envs/msc/lib/python3.7/logging/__init__.py", line 221, in _releaseLock
    def _releaseLock():
KeyboardInterrupt
Traceback (most recent call last):
  File "/u/jbu/.conda/envs/msc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 872, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/u/jbu/.conda/envs/msc/lib/python3.7/queue.py", line 178, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "trainer_resnet.py", line 333, in <module>
    main()
  File "trainer_resnet.py", line 142, in main
    mean_prec1, std_prec1 = validate_noisy(val_loader, model, args, eta_inf=args.eta_train, eta_mode=args.eta_mode, n_inf=3)
  File "trainer_resnet.py", line 255, in validate_noisy
    accs[i] = validate(val_loader, model_noisy, args)
  File "trainer_resnet.py", line 272, in validate
    for i, (input, target) in enumerate(val_loader):
  File "/u/jbu/.conda/envs/msc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/u/jbu/.conda/envs/msc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1068, in _next_data
    idx, data = self._get_data()
  File "/u/jbu/.conda/envs/msc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1024, in _get_data
    success, data = self._try_get_data()
  File "/u/jbu/.conda/envs/msc/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 885, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 42392, 42398, 42400) exited unexpectedly
